Repository oSoc18/SmartFlanders, pull requests merged in 2018-07, with the labels that each got.

#14 Bug/issue 13
  .circleci/config.yml
Labels: CI

#39 Added docs folder for Github Pages setup
  docs/README.md
Labels: Task

#49 Adding tests for Transformer
  test/test.js
Labels: CI

#56 Feature/issue 42
  frontend/form.html
  frontend/script.js
  frontend/styles.css
  meetings/meeting3.md
Labels: Task

#54 Feature/issue 52
  helpers/transformer.js
  matcher.js
  package-lock.json
  test/test.js
Labels: Task

#59 Fixed tests and re-enabled them
  helpers/matcher.js
  helpers/transformer.js
  test/test.js
Labels: CI

#68 Added JSON schema for current implementation
  test/schema.json
Labels: CI

#67 Fixed string quotes
  helpers/transformer.js
  package-lock.json
  package.json
Labels: Task

#69 Deploy to bare bone server using Circle CI
  .circleci/config.yml
  package-lock.json
Labels: Task

#82 Use tagged builds for deploy
  .circleci/config.yml
Labels: CI

#83 Feature/issue 81 part 2
  .circleci/config.yml
Labels: CI

#87 Fixed typo in story
  meetings/story.md
Labels: Task

#103 Move deployment to BASH script
  .circleci/config.yml
  .circleci/deploy.sh
Labels: CI

#92 Responsibilty schema in LibreOffice Draw
  meetings/SmartFlandersResponsibilities.odg
Labels: blog

#115 Frontend form to pug
  controllers/transformerController.js
  helpers/aalst.json
  helpers/transformer.js
  index.js
  package-lock.json
  routes.js
  templates/building-units.pug
  templates/building.pug
  templates/buildings.pug
  templates/index.pug
  templates/info.pug
  templates/partials/head.pug
  templates/partials/header.pug
  templates/search.pug
  templates/styles.css
Labels: Task

#120 Clean up + added tests
  controllers/transformerController.js
  helpers/lieselotte.js
  package-lock.json
  package.json
  test/test.js
Labels: CI, Task

#119 Feature/issue 100
  helpers/postcodeMapper.js
  index.js
  public/css/styles.css
  templates/building-units.pug
  templates/buildings.pug
  templates/search.pug
Labels: Task

#122 Patched gebouw-example for OASIS
  files/gebouw-example.json
Labels: Task

#127 Make release V0.0.7
  files/2000/catalog.json
  files/2000/gebouwen/16211763.json
  files/8500/catalog.json
  files/8500/gebouwen/11972114.json
  files/8500/gebouwen/11984924.json
  files/9000/catalog.json
  files/9000/gebouwen/12568861.json
  files/9000/gebouwen/16268696.json
  files/9300/catalog.json
  files/9940/catalog.json
  files/9940/gebouwen/12568861.json
  files/master-catalog.json
  helpers/transformer.js
  public/app.js
  public/css/styles.css
  templates/building-units.pug
  templates/search.pug
Labels: Task, help wanted

#128 Redirect root /graph to master catalogue
  index.js
Labels: bug

#131 Deploy V0.0.8
  files/9940/catalog.json
  index.js
  public/css/styles.css
  public/css/styles.css.map
  routes.js
  templates/address.pug
  templates/building-units.pug
  templates/css/styles.scss
  templates/index.pug
  templates/info.pug
  templates/partials/header.pug
  templates/postcode.pug
  templates/services.pug
  templates/snippet.pug
Labels: Task

#133 Feature/issue 123
  controllers/openingHoursController.js
  controllers/serviceController.js
  files/2800/catalog.json
  files/2800/gebouwen/6921454.json
  files/9940/gebouwen/12568861.json
  files/master-catalog.json
  files/service-example.json
  helpers/transformer.js
  package-lock.json
  public/css/styles.css
  public/css/styles.css.map
  routes.js
  templates/css/styles.scss
  templates/info.pug
  test/test.js
Labels: Task

#137 chore(): ready for master
  files/2000/catalog.json
  files/2000/gebouwen/16211763.json
  files/2800/catalog.json
  files/2800/gebouwen/6921454.json
  files/8500/catalog.json
  files/8500/gebouwen/11972114.json
  files/8500/gebouwen/11984924.json
  files/9000/catalog.json
  files/9000/gebouwen/12568861.json
  files/9000/gebouwen/16268696.json
  files/9300/catalog.json
  files/9940/catalog.json
  files/9940/gebouwen/12568861.json
  files/master-catalog.json
  frontend/form.html
  frontend/jquery.js
  frontend/script.js
  frontend/styles.scss
  helpers/aalst.json
  helpers/transformer.js
Labels: Task

#163 Added link to building for service
  helpers/transformer.js
Labels: Task
